apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MS_NOTICIAS_HOST
          value: "ms-noticias"
        - name: MS_NOTICIAS_PORT
          value: "4001"
        - name: MS_EVENTOS_HOST
          value: "ms-eventos"
        - name: MS_EVENTOS_PORT
          value: "4002"
