apiVersion: v1
kind: Service
metadata:
  name: strapi
spec:
  ports:
    - port: 1337
      targetPort: 1337
  selector:
    app: strapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
spec:
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
      - name: strapi
        image: strapi-cms:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 1337
        env:
        - name: MS_NOTICIAS_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: MS_NOTICIAS_HOST
        - name: MS_NOTICIAS_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: MS_NOTICIAS_PORT
        - name: MS_EVENTOS_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: MS_EVENTOS_HOST
        - name: MS_EVENTOS_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: MS_EVENTOS_PORT
