apiVersion: v1
kind: Service
metadata:
  name: mongo-noticias
  labels:
    app: mongo-noticias
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo-noticias
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-noticias
spec:
  selector:
    matchLabels:
      app: mongo-noticias
  template:
    metadata:
      labels:
        app: mongo-noticias
    spec:
      containers:
      - name: mongo
        image: mongo:7
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-noticias-data
          mountPath: /data/db
      volumes:
      - name: mongo-noticias-data
        emptyDir: {} # Switch to PVC for production
